//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryIT.xpathService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="xpathService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/xpathsearch", ReplyAction="http://tempuri.org/IService1/xpathsearchResponse")]
        string[] xpathsearch(string xmlUrl, string pathExpr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/xpathsearch", ReplyAction="http://tempuri.org/IService1/xpathsearchResponse")]
        System.Threading.Tasks.Task<string[]> xpathsearchAsync(string xmlUrl, string pathExpr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TryIT.xpathService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TryIT.xpathService.IService1>, TryIT.xpathService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] xpathsearch(string xmlUrl, string pathExpr) {
            return base.Channel.xpathsearch(xmlUrl, pathExpr);
        }
        
        public System.Threading.Tasks.Task<string[]> xpathsearchAsync(string xmlUrl, string pathExpr) {
            return base.Channel.xpathsearchAsync(xmlUrl, pathExpr);
        }
    }
}
